### ISSUE TITLE
Question about the CSI

### ISSUE THREAD

**Issue by gjjustc** [sibrendebast/inside-the-black-box#1]
Hi, I have a question about the CSI used here. The shape of the CSI is 64x100. Is it in the angular-frequency domain or other domain? Thank you!

**Comment by sibrendebast** [comment]
Hi,
Thank you for your question. This is in the frequency domain, and are IQ samples.
The samples are recorded with 64 antennas and for 100 frequency subcarriers.
You can find more information at https://homes.esat.kuleuven.be/~sdebast/measurements/measurements_index.html

kind regards,
Sibren

**Comment by gjjustc** [comment]
Thank you.
